import createFetchClient from 'openapi-fetch'
import createClient from 'openapi-react-query'
import type { paths } from './schema/generated'
import { CONFIG } from '@/shared/model/config' // generated by openapi-typescript

export const fetchClient = createFetchClient<paths>({
  baseUrl: CONFIG.API_BASE_URL
})

export const rqClient = createClient(fetchClient)

const res = rqClient.useQuery('get', '/boards')

console.log(res.data.forEach((item) => item.name))
